name: Pre-merge checks

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up JDK 11
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build and test project
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew androidApp:assembleDebug androidApp:testDebugUnitTest

  test:
    runs-on: macOS-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [21, 29]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up JDK 11
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2.18.1
        with:
          api-level: ${{ matrix.api-level }}
          disable-animations: true
          script: ./gradlew androidApp:connectedCheck

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: ${{ env.SAMPLE_PATH }}/app/build/reports
